name: Deploy to VDS

on:
  workflow_run:
    workflows: [ "CI build" ]
    types: [ completed ]
    branches: [ "main" ]

env:
  BLOG_VERSION: 0.0.${{ github.run_number }}
  DB_URL: "jdbc:postgresql://83.222.8.191:5432/default_db"
  DB_USER: test
  DB_PASS: test
  DATABASE_SCHEMA: ms_blog

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

  create-tag:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.BLOG_VERSION }}',
              sha: context.sha
            })
  prepare-environment:
    runs-on: self-hosted
    needs: create-tag
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused images
        run: docker image prune -a -f

  deploy:
    runs-on: self-hosted
    needs: [prepare-environment,build]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-build
        run: docker build -t smart4it/blog:${{ env.BLOG_VERSION }} .
      - name: docker-compose
        run: docker-compose -f "/home/udocker/docker-compose.yaml" -p smart4it up -d smart4it/blog